version: "3.8"

services:
  postgres-db:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      POSTGRES_USER: ${POSTGRESDB_USER}
      POSTGRES_PASSWORD: ${POSTGRESDB_ROOT_PASSWORD}
      POSTGRES_DB: ${POSTGRESDB_DATABASE}
    ports:
      - "${POSTGRESDB_LOCAL_PORT}:${POSTGRESDB_DOCKER_PORT}"
    volumes:
      - db:/var/lib/postgresql/data

  back-end:
    depends_on:
      - postgres-db
    build: ./back-end
    restart: on-failure
    env_file: ./.env
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:postgresql://postgres-db:${POSTGRESDB_DOCKER_PORT}/${POSTGRESDB_DATABASE}",
        "spring.datasource.username": "${POSTGRESDB_USER}",
        "spring.datasource.password": "${POSTGRESDB_ROOT_PASSWORD}",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  front-end:
    build: ./front-end
    restart: unless-stopped
    ports:
      - "${ANGULAR_LOCAL_PORT}:4200"
    volumes:
      - ./front-end/src:/src/app
    stdin_open: true
    tty: true

volumes:
  db:
