spring.application.name=Back-end
server.port=8081
# Spring Datasource Configuration
spring.datasource.password=123
spring.datasource.url=jdbc:postgresql://localhost:5432/crm-db
spring.datasource.username=postgres

# Spring JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.main.banner-mode=console

#Liquibase configuration:
spring.liquibase.change-log=classpath:/db/changelog/db/changelog.yaml


# Identifiants Cognito
cognito.userPoolId=us-east-1_5iLNzGL7a
cognito.clientId=17i9htug0sahhqp3sfkg38r75m
cognito.clientSecret=1hr3rop2jstmgetd5a6l8eb5k5jend9ngeiib2c0dc0ffj4q7am0
cognito.region=us-east-1
cognito.clientName=CRM-G

# Configuration Spring Security OAuth2
spring.security.oauth2.client.registration.cognito.client-id=${cognito.clientId}
spring.security.oauth2.client.registration.cognito.client-secret=${cognito.clientSecret}
spring.security.oauth2.client.registration.cognito.scope=openid
spring.security.oauth2.client.registration.cognito.redirect-uri=http://localhost:4200/home
spring.security.oauth2.client.registration.cognito.client-name=${cognito.clientName}
spring.security.oauth2.client.registration.cognito.authorization-grant-type=authorization_code
spring.security.oauth2.client.provider.cognito.issuer-uri=https://cognito-idp.${cognito.region}.amazonaws.com/${cognito.userPoolId}

# Déconnexion Cognito
aws.cognito.logoutUrl=https://crm-geo.auth.${cognito.region}.amazoncognito.com/logout
aws.cognito.logout.success.redirectUrl=http://localhost:4200
