spring.application.name=Back-end
server.port=8081
# Spring Datasource Configuration
spring.datasource.password=123
spring.datasource.url=jdbc:postgresql://localhost:5432/crm-db
spring.datasource.username=postgres

# Spring JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.main.banner-mode=console

#Liquibase configuration:
spring.liquibase.change-log=classpath:/db/changelog/db/changelog.yaml


# Identifiants Cognito
cognito.userPoolId=us-east-1_5iLNzGL7a
cognito.clientId=7hgos2skpub85bgo8p6n7spf7v
cognito.clientSecret=t00ba94d4c0ps73c4qdtetu6dubei89c6p6cmmfmd3s9u12bn56
cognito.region=us-east-1

# Configuration Spring Security OAuth2
spring.security.oauth2.client.registration.cognito.client-id=${cognito.clientId}
spring.security.oauth2.client.registration.cognito.client-secret=${cognito.clientSecret}
spring.security.oauth2.client.registration.cognito.scope=openid
spring.security.oauth2.client.registration.cognito.redirect-uri=https://localhost:8081/login/oauth/code/cognito
spring.security.oauth2.client.registration.cognito.client-name=CRM-Geo
spring.security.oauth2.client.registration.cognito.authorization-grant-type=authorization_code
spring.security.oauth2.client.provider.cognito.issuer-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_5iLNzGL7a

# Déconnexion Cognito
aws.cognito.logoutUrl=https://crm-geo.auth.us-east-1.amazoncognito.com/logout
aws.cognito.logout.success.redirectUrl=http://localhost:8081/logout

